// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GenbankTypeProvider")>]
[<assembly: AssemblyProductAttribute("GenbankTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type provider for Genbank")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GenbankTypeProvider"
    let [<Literal>] AssemblyProduct = "GenbankTypeProvider"
    let [<Literal>] AssemblyDescription = "Type provider for Genbank"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
