// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GenbankTypeProvider")>]
[<assembly: AssemblyProductAttribute("GenbankTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("A type provider for genetic sequences from Genbank.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GenbankTypeProvider"
    let [<Literal>] AssemblyProduct = "GenbankTypeProvider"
    let [<Literal>] AssemblyDescription = "A type provider for genetic sequences from Genbank."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
